# Draw a two-dimensional kernel-density contour from the wide segment table.
# Arguments: input.tsv, output.png, x-reference ID, y-reference ID, title.
library(MASS)

a <- commandArgs(trailingOnly=TRUE)

# Reference IDs map directly to the <id>_match_rate columns generated by
# core.py. read.delim converts the workflow's literal NA values to R NA.
d <- read.delim(a[1], check.names=FALSE, na.strings="NA")
x <- d[[paste0(a[3], "_match_rate")]]
y <- d[[paste0(a[4], "_match_rate")]]
keep <- is.finite(x) & is.finite(y)
x <- x[keep]; y <- y[keep]

png(a[2], width=1100, height=1100, res=250)

# kde2d needs variation on both axes. Still create a valid PNG when a
# population has too few comparable segments so downstream targets complete.
if (length(x) < 3 || length(unique(x)) < 2 || length(unique(y)) < 2) {
  plot.new(); title(main=a[5]); text(.5, .5, "Insufficient data for contour")
} else {
  contour(kde2d(x, y, n=100, lims=c(0,1,0,1)),
          levels=c(seq(.3,.9,.1), seq(1,10,1)),
          xaxs="i", yaxs="i", xlab=paste("Match to",a[3]),
          ylab=paste("Match to",a[4]), main=a[5], las=1, lty=5)
  grid(lty=3, col="gray")
}
dev.off()
